[package]
name = "rust_udp_hole_puncher"
version = "0.1.0"
edition = "2021"

authors = ["Kendrick Grünberg"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.0.5", features = ["derive"] }
